# Generated by Django 5.1.3 on 2024-11-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='horario',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
